name: workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build using makefile
      - name: Build the program
        run: make

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: myprogram
          path: ./myprogram 
